all:
  children:
    primary_domain_controller:
      hosts:
        dc01.how2hax.pl
      vars:
        ansible_user: "{{ domain_admin_username }}"
        ansible_password: "{{ domain_admin_password }}"
        ansible_winrm_server_cert_validation: ignore
        ansible_connection: winrm
    domain_controllers:
      hosts:
        dc01.how2hax.pl
    workstations:
      hosts:
        wk01.how2hax.pl