---
  - name: Welcome task
    ansible.builtin.debug:
      msg: "Adding vulnerabilities..."
  - name: Add vulns
    ansible.windows.win.shell:  "{{ lookup('ansible.builtin.file', 'AddVulns.ps1) }}" #from files