---
  - name: Welcome task
    ansible.builtin.debug:
      msg: "Adding vulnerabilities..."
  - name: Add vulnerabilities
    ansible.windows.win_shell: "{{ lookup('ansible.builtin.file', 'AddVulns.ps1') }}" #from files