---
   -  name: Welcome task 
      ansible.builtin.debug:
         msg: Hello! Let`s prepare the domain...

   -  name: Configure the domain #Just domain configuration
      include_tasks: configure.yml
      when: configure == "Yes"

   -  name: Add vulns   #Adding vulnerabilities according to documentation
      include_tasks: add_vulns.yml
      when: add_vulns == "Yes"

   -  name: Remove vulns   #Removing vulnerabilities according to documentation
      include_tasks: remove_vulns.yml
      when: remove_vulns == "Yes"
