---
  - name: Welcome task
    ansible.builtin.debug:
      msg: "Removing vulnerabilities..."
  - name: Remove vulnerabilities
    ansible.windows.win_shell: "{{ lookup('ansible.builtin.file', 'RemoveVulns.ps1') }}" #from files
