---
  - name: Welcome task
    ansible.builtin.debug:
      msg: "Removing vulnerabilities..."
  - name: Remove vulns
    ansible.windows.win.shell:  "{{ lookup('ansible.builtin.file', 'RemoveVulns.ps1) }}" #from files